//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Enum;
import SteelRT.Util.Types;
import SteelRT.Util.Values;
import SteelRT.Util.Sequence;
import SteelRT.Instrument.FwDeclarations;
import <cstdio>;
export
namespace app{enum class call : enum_uint_t {mat_product_v3_block_compact_app_pack_3 = 2,mat_product_v3_block_compact_app_pack_4 = 3,mat_product_v3_block_compact_app_pack_5 = 4,mat_product_v3_block_compact_app_unpack_7 = 5,mat_product_v3_block_compact_mat_product_app_6 = 6,mat_product_v3_block_compact_matrix_allocate_0 = 7,mat_product_v3_block_compact_matrix_allocate_1 = 8,mat_product_v3_block_compact_matrix_allocate_2 = 9,mat_product_v3_block_compact_matrix_deallocate_10 = 10,mat_product_v3_block_compact_matrix_deallocate_8 = 11,mat_product_v3_block_compact_matrix_deallocate_9 = 12};using enabled_calls = util::sequence::enum_t<call,call::mat_product_v3_block_compact_app_pack_3,call::mat_product_v3_block_compact_app_pack_4,call::mat_product_v3_block_compact_app_pack_5,call::mat_product_v3_block_compact_app_unpack_7,call::mat_product_v3_block_compact_mat_product_app_6,call::mat_product_v3_block_compact_matrix_allocate_0,call::mat_product_v3_block_compact_matrix_allocate_1,call::mat_product_v3_block_compact_matrix_allocate_2,call::mat_product_v3_block_compact_matrix_deallocate_10,call::mat_product_v3_block_compact_matrix_deallocate_8,call::mat_product_v3_block_compact_matrix_deallocate_9>;}
export
namespace instrument::event{template <> struct type<app::call>{static constexpr const char * name = "call";
static constexpr const enum_type_id_t type_id = 0;
static constexpr bool instrumentable = true;
};template <> struct value<app::call::mat_product_v3_block_compact_app_pack_3>{static constexpr const char * name = "mat_product_v3_block_compact_app_pack_3";}
;template <> struct value<app::call::mat_product_v3_block_compact_app_pack_4>{static constexpr const char * name = "mat_product_v3_block_compact_app_pack_4";}
;template <> struct value<app::call::mat_product_v3_block_compact_app_pack_5>{static constexpr const char * name = "mat_product_v3_block_compact_app_pack_5";}
;template <> struct value<app::call::mat_product_v3_block_compact_app_unpack_7>{static constexpr const char * name = "mat_product_v3_block_compact_app_unpack_7";}
;template <> struct value<app::call::mat_product_v3_block_compact_mat_product_app_6>{static constexpr const char * name = "mat_product_v3_block_compact_mat_product_app_6";}
;template <> struct value<app::call::mat_product_v3_block_compact_matrix_allocate_0>{static constexpr const char * name = "mat_product_v3_block_compact_matrix_allocate_0";}
;template <> struct value<app::call::mat_product_v3_block_compact_matrix_allocate_1>{static constexpr const char * name = "mat_product_v3_block_compact_matrix_allocate_1";}
;template <> struct value<app::call::mat_product_v3_block_compact_matrix_allocate_2>{static constexpr const char * name = "mat_product_v3_block_compact_matrix_allocate_2";}
;template <> struct value<app::call::mat_product_v3_block_compact_matrix_deallocate_10>{static constexpr const char * name = "mat_product_v3_block_compact_matrix_deallocate_10";}
;template <> struct value<app::call::mat_product_v3_block_compact_matrix_deallocate_8>{static constexpr const char * name = "mat_product_v3_block_compact_matrix_deallocate_8";}
;template <> struct value<app::call::mat_product_v3_block_compact_matrix_deallocate_9>{static constexpr const char * name = "mat_product_v3_block_compact_matrix_deallocate_9";}
;}export
namespace app{enum class id : enum_uint_t {app_pack = 2,app_unpack = 3,mat_product_app = 4,matrix_allocate = 5,matrix_deallocate = 6};using enabled_ids = util::sequence::enum_t<id,id::app_pack,id::app_unpack,id::mat_product_app,id::matrix_allocate,id::matrix_deallocate>;}
export
namespace instrument::event{template <> struct type<app::id>{static constexpr const char * name = "id";
static constexpr const enum_type_id_t type_id = 1;
static constexpr bool instrumentable = true;
};template <> struct value<app::id::app_pack>{static constexpr const char * name = "app_pack";}
;template <> struct value<app::id::app_unpack>{static constexpr const char * name = "app_unpack";}
;template <> struct value<app::id::mat_product_app>{static constexpr const char * name = "mat_product_app";}
;template <> struct value<app::id::matrix_allocate>{static constexpr const char * name = "matrix_allocate";}
;template <> struct value<app::id::matrix_deallocate>{static constexpr const char * name = "matrix_deallocate";}
;}export
namespace app{enum class impl : enum_uint_t {allocate_matrix = 2,deallocate_matrix = 3,mat_product_v0_kernel_compact = 4,mat_product_v3_block_compact = 5,pack_matrix = 6,unpack_matrix = 7};using enabled_impls = util::sequence::enum_t<impl,impl::allocate_matrix,impl::deallocate_matrix,impl::mat_product_v0_kernel_compact,impl::mat_product_v3_block_compact,impl::pack_matrix,impl::unpack_matrix>;}
export
namespace instrument::event{template <> struct type<app::impl>{static constexpr const char * name = "impl";
static constexpr const enum_type_id_t type_id = 2;
static constexpr bool instrumentable = true;
};template <> struct value<app::impl::allocate_matrix>{static constexpr const char * name = "allocate_matrix";}
;template <> struct value<app::impl::deallocate_matrix>{static constexpr const char * name = "deallocate_matrix";}
;template <> struct value<app::impl::mat_product_v0_kernel_compact>{static constexpr const char * name = "mat_product_v0_kernel_compact";}
;template <> struct value<app::impl::mat_product_v3_block_compact>{static constexpr const char * name = "mat_product_v3_block_compact";}
;template <> struct value<app::impl::pack_matrix>{static constexpr const char * name = "pack_matrix";}
;template <> struct value<app::impl::unpack_matrix>{static constexpr const char * name = "unpack_matrix";}
;}