//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import Plat.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Dep.Dim.View;
export
namespace app{
template <> struct traits<id::caller_blocks>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_blocks>;};template <> struct traits<id::caller_low_triangle>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_low_triangle>;};template <> struct traits<id::caller_rectangle>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_rectangle>;};template <> struct traits<id::caller_up_triangle>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_up_triangle>;};template <> struct traits<id::foo_1d_blocks_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_blocks>;};template <> struct traits<id::foo_low_tri_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_low_triangle>;};template <> struct traits<id::foo_rectangle_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_rectangle>;};template <> struct traits<id::foo_up_tri_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_up_triangle>;};template <> struct traits<impl::foo_rectangle> {static constexpr impl this_impl = impl::foo_rectangle;
static constexpr id belonging_id = id::foo_rectangle_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_rectangle_foo_rectangle_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_rectangle> {static constexpr impl this_impl = impl::caller_rectangle;
static constexpr id belonging_id = id::caller_rectangle;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int,int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_rectangle_foo_rectangle_app_0>;
};template <> struct traits<impl::foo_blocks> {static constexpr impl this_impl = impl::foo_blocks;
static constexpr id belonging_id = id::foo_1d_blocks_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_blocks_foo_1d_blocks_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_blocks> {static constexpr impl this_impl = impl::caller_blocks;
static constexpr id belonging_id = id::caller_blocks;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int,int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_blocks_foo_1d_blocks_app_0>;
};template <> struct traits<impl::foo_low_triangle> {static constexpr impl this_impl = impl::foo_low_triangle;
static constexpr id belonging_id = id::foo_low_tri_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_low_triangle_foo_low_tri_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_low_triangle> {static constexpr impl this_impl = impl::caller_low_triangle;
static constexpr id belonging_id = id::caller_low_triangle;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int,int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_low_triangle_foo_low_tri_app_0>;
};template <> struct traits<impl::foo_up_triangle> {static constexpr impl this_impl = impl::foo_up_triangle;
static constexpr id belonging_id = id::foo_up_tri_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_up_triangle_foo_up_tri_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_up_triangle> {static constexpr impl this_impl = impl::caller_up_triangle;
static constexpr id belonging_id = id::caller_up_triangle;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int,int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_up_triangle_foo_up_tri_app_0>;
};template <> struct traits<call::caller_rectangle_foo_rectangle_app_0> {static constexpr call this_call = call::caller_rectangle_foo_rectangle_app_0;
static constexpr impl belonging_impl = impl::foo_rectangle;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<2,float>>,int,int>;
};template <> struct traits<call::caller_blocks_foo_1d_blocks_app_0> {static constexpr call this_call = call::caller_blocks_foo_1d_blocks_app_0;
static constexpr impl belonging_impl = impl::foo_blocks;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<2,float>>,int,int>;
};template <> struct traits<call::caller_low_triangle_foo_low_tri_app_0> {static constexpr call this_call = call::caller_low_triangle_foo_low_tri_app_0;
static constexpr impl belonging_impl = impl::foo_low_triangle;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<2,float>>,int,int>;
};template <> struct traits<call::caller_up_triangle_foo_up_tri_app_0> {static constexpr call this_call = call::caller_up_triangle_foo_up_tri_app_0;
static constexpr impl belonging_impl = impl::foo_up_triangle;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<2,float>>,int,int>;
};}