//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Proxy;
export import App.Graph;
export import SteelRT.Util.Types;
export import SteelRT.Util.Sequence;
export import SteelRT.Util.FwDeclarations.App;
export import SteelRT.Util.Predicates.App;
export import SteelRT.Task.Descriptor;
export import SteelRT.Task.Dispatcher;
export import SteelRT.Work.Descriptor.Global;
export import SteelRT.Dep.MakeAsync;
export import SteelRT.Dep.Guard.Backend;
export import SteelRT.Dep.Guard.Frontend;
export import SteelRT.Dep.Wrap;
export import <type_traits>;
export import <stdexcept>;
void foo_rectangle(std::add_pointer_t<std::add_const_t<float>>,int,int);
task::coro::dispatcher<app::impl::caller_rectangle> caller_rectangle(task::attr::descriptor& ,int,int);
void foo_blocks(std::add_pointer_t<std::add_const_t<float>>,int,int);
task::coro::dispatcher<app::impl::caller_blocks> caller_blocks(task::attr::descriptor& ,int,int);
void foo_low_triangle(std::add_pointer_t<std::add_const_t<float>>,int,int);
task::coro::dispatcher<app::impl::caller_low_triangle> caller_low_triangle(task::attr::descriptor& ,int,int);
void foo_up_triangle(std::add_pointer_t<std::add_const_t<float>>,int,int);
task::coro::dispatcher<app::impl::caller_up_triangle> caller_up_triangle(task::attr::descriptor& ,int,int);
export
namespace app{
template <>
class kernel_proxy<impl::foo_rectangle> {
  static constexpr impl this_impl = impl::foo_rectangle;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_rectangle( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_rectangle> {
public:
  static constexpr impl this_impl = impl::caller_rectangle;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_rectangle( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_blocks> {
  static constexpr impl this_impl = impl::foo_blocks;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_blocks( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_blocks> {
public:
  static constexpr impl this_impl = impl::caller_blocks;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_blocks( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_low_triangle> {
  static constexpr impl this_impl = impl::foo_low_triangle;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_low_triangle( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_low_triangle> {
public:
  static constexpr impl this_impl = impl::caller_low_triangle;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_low_triangle( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_up_triangle> {
  static constexpr impl this_impl = impl::foo_up_triangle;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_up_triangle( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_up_triangle> {
public:
  static constexpr impl this_impl = impl::caller_up_triangle;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_up_triangle( std::forward<DispatcherArgs>(args) ... ) );
  }
};
}