


namespace bld {

static constexpr const char * HeaderTxt = "//////////////////////////////////////\n"
                                            "// \n"
                                            "// Autogenerated file. Do not modify. \n"
                                            "// \n"
                                            "//////////////////////////////////////\n\n";

} // namespace bld
