//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Data.View;
export
namespace app{
template <> struct traits<id::main_entry>{using impl_sequence = util::sequence::enum_t<impl,impl::main_entry>;};template <> struct traits<impl::main_entry> {static constexpr impl this_impl = impl::main_entry;
static constexpr id belonging_id = id::main_entry;
using arg_tuple_type = util::tuple_t<std::add_lvalue_reference_t<int>,int,std::add_pointer_t<std::add_const_t<char*>>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::main_entry> {static constexpr impl this_impl = impl::main_entry;
static constexpr id belonging_id = id::main_entry;
using arg_tuple_type = util::tuple_t<std::add_lvalue_reference_t<int>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call>;
};}