//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Enum;
import SteelRT.Util.Types;
import SteelRT.Util.Values;
import SteelRT.Util.Sequence;
import SteelRT.Instrument.FwDeclarations;
import <cstdio>;
export
namespace app{enum class call : enum_uint_t {caller_block_foo_block_app_0 = 2};using enabled_calls = util::sequence::enum_t<call,call::caller_block_foo_block_app_0>;}
export
namespace instrument::event{template <> struct type<app::call>{static constexpr const char * name = "call";
static constexpr const enum_type_id_t type_id = 0;
static constexpr bool instrumentable = true;
};template <> struct value<app::call::caller_block_foo_block_app_0>{static constexpr const char * name = "caller_block_foo_block_app_0";}
;}export
namespace app{enum class id : enum_uint_t {caller_block = 2,foo_block_app = 3};using enabled_ids = util::sequence::enum_t<id,id::caller_block,id::foo_block_app>;}
export
namespace instrument::event{template <> struct type<app::id>{static constexpr const char * name = "id";
static constexpr const enum_type_id_t type_id = 1;
static constexpr bool instrumentable = true;
};template <> struct value<app::id::caller_block>{static constexpr const char * name = "caller_block";}
;template <> struct value<app::id::foo_block_app>{static constexpr const char * name = "foo_block_app";}
;}export
namespace app{enum class impl : enum_uint_t {caller_block = 2,foo_block = 3};using enabled_impls = util::sequence::enum_t<impl,impl::caller_block,impl::foo_block>;}
export
namespace instrument::event{template <> struct type<app::impl>{static constexpr const char * name = "impl";
static constexpr const enum_type_id_t type_id = 2;
static constexpr bool instrumentable = true;
};template <> struct value<app::impl::caller_block>{static constexpr const char * name = "caller_block";}
;template <> struct value<app::impl::foo_block>{static constexpr const char * name = "foo_block";}
;}