//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Data.View;
export
namespace app{
template <> struct traits<id::caller1_foo>{using impl_sequence = util::sequence::enum_t<impl,impl::caller1_foo>;};template <> struct traits<id::caller2_foo>{using impl_sequence = util::sequence::enum_t<impl,impl::caller2_foo>;};template <> struct traits<id::caller3_foo>{using impl_sequence = util::sequence::enum_t<impl,impl::caller3_foo>;};template <> struct traits<id::caller4_foo>{using impl_sequence = util::sequence::enum_t<impl,impl::caller4_foo>;};template <> struct traits<id::caller_block>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_block>;};template <> struct traits<id::foo_block_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_block>;};template <> struct traits<id::fooapp_3d>{using impl_sequence = util::sequence::enum_t<impl,impl::foo>;};template <> struct traits<impl::foo_block> {static constexpr impl this_impl = impl::foo_block;
static constexpr id belonging_id = id::foo_block_app;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int,int,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_block_foo_block_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_block> {static constexpr impl this_impl = impl::caller_block;
static constexpr id belonging_id = id::caller_block;
using arg_tuple_type = util::tuple_t<int,int,int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_block_foo_block_app_0>;
};template <> struct traits<impl::foo> {static constexpr impl this_impl = impl::foo;
static constexpr id belonging_id = id::fooapp_3d;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call,call::caller1_foo_fooapp_3d_0,call::caller2_foo_fooapp_3d_0,call::caller3_foo_fooapp_3d_0,call::caller4_foo_fooapp_3d_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller1_foo> {static constexpr impl this_impl = impl::caller1_foo;
static constexpr id belonging_id = id::caller1_foo;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller1_foo_fooapp_3d_0>;
};template <> struct traits<impl::caller2_foo> {static constexpr impl this_impl = impl::caller2_foo;
static constexpr id belonging_id = id::caller2_foo;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller2_foo_fooapp_3d_0>;
};template <> struct traits<impl::caller3_foo> {static constexpr impl this_impl = impl::caller3_foo;
static constexpr id belonging_id = id::caller3_foo;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller3_foo_fooapp_3d_0>;
};template <> struct traits<impl::caller4_foo> {static constexpr impl this_impl = impl::caller4_foo;
static constexpr id belonging_id = id::caller4_foo;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller4_foo_fooapp_3d_0>;
};template <> struct traits<call::caller_block_foo_block_app_0> {static constexpr call this_call = call::caller_block_foo_block_app_0;
static constexpr impl belonging_impl = impl::foo_block;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<data::view<3,const float>>,int,int,int>;
};template <> struct traits<call::caller1_foo_fooapp_3d_0> {static constexpr call this_call = call::caller1_foo_fooapp_3d_0;
static constexpr impl belonging_impl = impl::foo;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<data::view<3,float>>,const unsigned,const unsigned,const unsigned>;
};template <> struct traits<call::caller2_foo_fooapp_3d_0> {static constexpr call this_call = call::caller2_foo_fooapp_3d_0;
static constexpr impl belonging_impl = impl::foo;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<data::view<3,float>>,const unsigned,const unsigned,const unsigned,const unsigned,const unsigned>;
};template <> struct traits<call::caller3_foo_fooapp_3d_0> {static constexpr call this_call = call::caller3_foo_fooapp_3d_0;
static constexpr impl belonging_impl = impl::foo;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<data::view<3,float>>,const unsigned,const unsigned,const unsigned>;
};template <> struct traits<call::caller4_foo_fooapp_3d_0> {static constexpr call this_call = call::caller4_foo_fooapp_3d_0;
static constexpr impl belonging_impl = impl::foo;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<data::view<3,float>>,const unsigned,const unsigned,const unsigned,const unsigned>;
};}