//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import Plat.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Dep.Dim.View;
export
namespace app{
template <> struct traits<id::caller_block>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_block>;};template <> struct traits<id::foo_block_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_block>;};template <> struct traits<impl::foo_block> {static constexpr impl this_impl = impl::foo_block;
static constexpr id belonging_id = id::foo_block_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int,int,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_block_foo_block_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_block> {static constexpr impl this_impl = impl::caller_block;
static constexpr id belonging_id = id::caller_block;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int,int,int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_block_foo_block_app_0>;
};template <> struct traits<call::caller_block_foo_block_app_0> {static constexpr call this_call = call::caller_block_foo_block_app_0;
static constexpr impl belonging_impl = impl::foo_block;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<3,float>>,int,int,int>;
};}