//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Enum;
import SteelRT.Util.Types;
import SteelRT.Util.Values;
import SteelRT.Util.Sequence;
import SteelRT.Instrument.FwDeclarations;
import <cstdio>;
export
namespace app{enum class call : enum_uint_t {caller1_ro_multiple_point_foo_ro_multiple_point_app_0 = 2,caller1_ro_multiple_point_foo_ro_multiple_point_app_1 = 3,caller1_ro_multiple_point_foo_ro_multiple_point_app_2 = 4,caller1_rw_multiple_point_foo_rw_multiple_point_app_0 = 5,caller1_rw_multiple_point_foo_rw_multiple_point_app_1 = 6,caller1_rw_multiple_point_foo_rw_multiple_point_app_2 = 7,caller2_ro_multiple_point_foo_ro_multiple_point_app_0 = 8,caller2_ro_multiple_point_foo_ro_multiple_point_app_1 = 9,caller2_ro_multiple_point_foo_ro_multiple_point_app_2 = 10,caller2_rw_multiple_point_foo_rw_multiple_point_app_0 = 11,caller2_rw_multiple_point_foo_rw_multiple_point_app_1 = 12,caller2_rw_multiple_point_foo_rw_multiple_point_app_2 = 13};using enabled_calls = util::sequence::enum_t<call,call::caller1_ro_multiple_point_foo_ro_multiple_point_app_0,call::caller1_ro_multiple_point_foo_ro_multiple_point_app_1,call::caller1_ro_multiple_point_foo_ro_multiple_point_app_2,call::caller1_rw_multiple_point_foo_rw_multiple_point_app_0,call::caller1_rw_multiple_point_foo_rw_multiple_point_app_1,call::caller1_rw_multiple_point_foo_rw_multiple_point_app_2,call::caller2_ro_multiple_point_foo_ro_multiple_point_app_0,call::caller2_ro_multiple_point_foo_ro_multiple_point_app_1,call::caller2_ro_multiple_point_foo_ro_multiple_point_app_2,call::caller2_rw_multiple_point_foo_rw_multiple_point_app_0,call::caller2_rw_multiple_point_foo_rw_multiple_point_app_1,call::caller2_rw_multiple_point_foo_rw_multiple_point_app_2>;}
export
namespace instrument::event{template <> struct type<app::call>{static constexpr const char * name = "call";
static constexpr const enum_type_id_t type_id = 0;
static constexpr bool instrumentable = true;
};template <> struct value<app::call::caller1_ro_multiple_point_foo_ro_multiple_point_app_0>{static constexpr const char * name = "caller1_ro_multiple_point_foo_ro_multiple_point_app_0";}
;template <> struct value<app::call::caller1_ro_multiple_point_foo_ro_multiple_point_app_1>{static constexpr const char * name = "caller1_ro_multiple_point_foo_ro_multiple_point_app_1";}
;template <> struct value<app::call::caller1_ro_multiple_point_foo_ro_multiple_point_app_2>{static constexpr const char * name = "caller1_ro_multiple_point_foo_ro_multiple_point_app_2";}
;template <> struct value<app::call::caller1_rw_multiple_point_foo_rw_multiple_point_app_0>{static constexpr const char * name = "caller1_rw_multiple_point_foo_rw_multiple_point_app_0";}
;template <> struct value<app::call::caller1_rw_multiple_point_foo_rw_multiple_point_app_1>{static constexpr const char * name = "caller1_rw_multiple_point_foo_rw_multiple_point_app_1";}
;template <> struct value<app::call::caller1_rw_multiple_point_foo_rw_multiple_point_app_2>{static constexpr const char * name = "caller1_rw_multiple_point_foo_rw_multiple_point_app_2";}
;template <> struct value<app::call::caller2_ro_multiple_point_foo_ro_multiple_point_app_0>{static constexpr const char * name = "caller2_ro_multiple_point_foo_ro_multiple_point_app_0";}
;template <> struct value<app::call::caller2_ro_multiple_point_foo_ro_multiple_point_app_1>{static constexpr const char * name = "caller2_ro_multiple_point_foo_ro_multiple_point_app_1";}
;template <> struct value<app::call::caller2_ro_multiple_point_foo_ro_multiple_point_app_2>{static constexpr const char * name = "caller2_ro_multiple_point_foo_ro_multiple_point_app_2";}
;template <> struct value<app::call::caller2_rw_multiple_point_foo_rw_multiple_point_app_0>{static constexpr const char * name = "caller2_rw_multiple_point_foo_rw_multiple_point_app_0";}
;template <> struct value<app::call::caller2_rw_multiple_point_foo_rw_multiple_point_app_1>{static constexpr const char * name = "caller2_rw_multiple_point_foo_rw_multiple_point_app_1";}
;template <> struct value<app::call::caller2_rw_multiple_point_foo_rw_multiple_point_app_2>{static constexpr const char * name = "caller2_rw_multiple_point_foo_rw_multiple_point_app_2";}
;}export
namespace app{enum class id : enum_uint_t {caller1_ro_multiple_point = 2,caller1_rw_multiple_point = 3,caller2_ro_multiple_point = 4,caller2_rw_multiple_point = 5,foo_ro_multiple_point_app = 6,foo_rw_multiple_point_app = 7};using enabled_ids = util::sequence::enum_t<id,id::caller1_ro_multiple_point,id::caller1_rw_multiple_point,id::caller2_ro_multiple_point,id::caller2_rw_multiple_point,id::foo_ro_multiple_point_app,id::foo_rw_multiple_point_app>;}
export
namespace instrument::event{template <> struct type<app::id>{static constexpr const char * name = "id";
static constexpr const enum_type_id_t type_id = 1;
static constexpr bool instrumentable = true;
};template <> struct value<app::id::caller1_ro_multiple_point>{static constexpr const char * name = "caller1_ro_multiple_point";}
;template <> struct value<app::id::caller1_rw_multiple_point>{static constexpr const char * name = "caller1_rw_multiple_point";}
;template <> struct value<app::id::caller2_ro_multiple_point>{static constexpr const char * name = "caller2_ro_multiple_point";}
;template <> struct value<app::id::caller2_rw_multiple_point>{static constexpr const char * name = "caller2_rw_multiple_point";}
;template <> struct value<app::id::foo_ro_multiple_point_app>{static constexpr const char * name = "foo_ro_multiple_point_app";}
;template <> struct value<app::id::foo_rw_multiple_point_app>{static constexpr const char * name = "foo_rw_multiple_point_app";}
;}export
namespace app{enum class impl : enum_uint_t {caller1_ro_multiple_point = 2,caller1_rw_multiple_point = 3,caller2_ro_multiple_point = 4,caller2_rw_multiple_point = 5,foo_ro_multiple_point = 6,foo_rw_multiple_point = 7};using enabled_impls = util::sequence::enum_t<impl,impl::caller1_ro_multiple_point,impl::caller1_rw_multiple_point,impl::caller2_ro_multiple_point,impl::caller2_rw_multiple_point,impl::foo_ro_multiple_point,impl::foo_rw_multiple_point>;}
export
namespace instrument::event{template <> struct type<app::impl>{static constexpr const char * name = "impl";
static constexpr const enum_type_id_t type_id = 2;
static constexpr bool instrumentable = true;
};template <> struct value<app::impl::caller1_ro_multiple_point>{static constexpr const char * name = "caller1_ro_multiple_point";}
;template <> struct value<app::impl::caller1_rw_multiple_point>{static constexpr const char * name = "caller1_rw_multiple_point";}
;template <> struct value<app::impl::caller2_ro_multiple_point>{static constexpr const char * name = "caller2_ro_multiple_point";}
;template <> struct value<app::impl::caller2_rw_multiple_point>{static constexpr const char * name = "caller2_rw_multiple_point";}
;template <> struct value<app::impl::foo_ro_multiple_point>{static constexpr const char * name = "foo_ro_multiple_point";}
;template <> struct value<app::impl::foo_rw_multiple_point>{static constexpr const char * name = "foo_rw_multiple_point";}
;}