//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Enum;
import SteelRT.Util.Types;
import SteelRT.Util.Values;
import SteelRT.Util.Sequence;
import SteelRT.Instrument.FwDeclarations;
import <cstdio>;
export
namespace app{enum class call : enum_uint_t {caller_foo_ro_arit_1_foo_ro_arit_app_0 = 2,caller_foo_ro_arit_2_foo_ro_arit_app_0 = 3,caller_foo_rw_arit_1_foo_rw_arit_app_0 = 4,caller_foo_rw_arit_2_foo_rw_arit_app_0 = 5};using enabled_calls = util::sequence::enum_t<call,call::caller_foo_ro_arit_1_foo_ro_arit_app_0,call::caller_foo_ro_arit_2_foo_ro_arit_app_0,call::caller_foo_rw_arit_1_foo_rw_arit_app_0,call::caller_foo_rw_arit_2_foo_rw_arit_app_0>;}
export
namespace instrument::event{template <> struct type<app::call>{static constexpr const char * name = "call";
static constexpr const enum_type_id_t type_id = 0;
static constexpr bool instrumentable = true;
};template <> struct value<app::call::caller_foo_ro_arit_1_foo_ro_arit_app_0>{static constexpr const char * name = "caller_foo_ro_arit_1_foo_ro_arit_app_0";}
;template <> struct value<app::call::caller_foo_ro_arit_2_foo_ro_arit_app_0>{static constexpr const char * name = "caller_foo_ro_arit_2_foo_ro_arit_app_0";}
;template <> struct value<app::call::caller_foo_rw_arit_1_foo_rw_arit_app_0>{static constexpr const char * name = "caller_foo_rw_arit_1_foo_rw_arit_app_0";}
;template <> struct value<app::call::caller_foo_rw_arit_2_foo_rw_arit_app_0>{static constexpr const char * name = "caller_foo_rw_arit_2_foo_rw_arit_app_0";}
;}export
namespace app{enum class id : enum_uint_t {caller_foo_ro_arit_1 = 2,caller_foo_ro_arit_2 = 3,caller_foo_rw_arit_1 = 4,caller_foo_rw_arit_2 = 5,foo_ro_arit_app = 6,foo_rw_arit_app = 7};using enabled_ids = util::sequence::enum_t<id,id::caller_foo_ro_arit_1,id::caller_foo_ro_arit_2,id::caller_foo_rw_arit_1,id::caller_foo_rw_arit_2,id::foo_ro_arit_app,id::foo_rw_arit_app>;}
export
namespace instrument::event{template <> struct type<app::id>{static constexpr const char * name = "id";
static constexpr const enum_type_id_t type_id = 1;
static constexpr bool instrumentable = true;
};template <> struct value<app::id::caller_foo_ro_arit_1>{static constexpr const char * name = "caller_foo_ro_arit_1";}
;template <> struct value<app::id::caller_foo_ro_arit_2>{static constexpr const char * name = "caller_foo_ro_arit_2";}
;template <> struct value<app::id::caller_foo_rw_arit_1>{static constexpr const char * name = "caller_foo_rw_arit_1";}
;template <> struct value<app::id::caller_foo_rw_arit_2>{static constexpr const char * name = "caller_foo_rw_arit_2";}
;template <> struct value<app::id::foo_ro_arit_app>{static constexpr const char * name = "foo_ro_arit_app";}
;template <> struct value<app::id::foo_rw_arit_app>{static constexpr const char * name = "foo_rw_arit_app";}
;}export
namespace app{enum class impl : enum_uint_t {caller_foo_ro_arit_1 = 2,caller_foo_ro_arit_2 = 3,caller_foo_rw_arit_1 = 4,caller_foo_rw_arit_2 = 5,foo_ro_arit = 6,foo_rw_arit = 7};using enabled_impls = util::sequence::enum_t<impl,impl::caller_foo_ro_arit_1,impl::caller_foo_ro_arit_2,impl::caller_foo_rw_arit_1,impl::caller_foo_rw_arit_2,impl::foo_ro_arit,impl::foo_rw_arit>;}
export
namespace instrument::event{template <> struct type<app::impl>{static constexpr const char * name = "impl";
static constexpr const enum_type_id_t type_id = 2;
static constexpr bool instrumentable = true;
};template <> struct value<app::impl::caller_foo_ro_arit_1>{static constexpr const char * name = "caller_foo_ro_arit_1";}
;template <> struct value<app::impl::caller_foo_ro_arit_2>{static constexpr const char * name = "caller_foo_ro_arit_2";}
;template <> struct value<app::impl::caller_foo_rw_arit_1>{static constexpr const char * name = "caller_foo_rw_arit_1";}
;template <> struct value<app::impl::caller_foo_rw_arit_2>{static constexpr const char * name = "caller_foo_rw_arit_2";}
;template <> struct value<app::impl::foo_ro_arit>{static constexpr const char * name = "foo_ro_arit";}
;template <> struct value<app::impl::foo_rw_arit>{static constexpr const char * name = "foo_rw_arit";}
;}