//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import Plat.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Dep.Dim.View;
export
namespace app{
template <> struct traits<id::caller_foo_ro_arit_1>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_foo_ro_arit_1>;};template <> struct traits<id::caller_foo_ro_arit_2>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_foo_ro_arit_2>;};template <> struct traits<id::caller_foo_rw_arit_1>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_foo_rw_arit_1>;};template <> struct traits<id::caller_foo_rw_arit_2>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_foo_rw_arit_2>;};template <> struct traits<id::foo_ro_arit_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_ro_arit>;};template <> struct traits<id::foo_rw_arit_app>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_rw_arit>;};template <> struct traits<impl::foo_ro_arit> {static constexpr impl this_impl = impl::foo_ro_arit;
static constexpr id belonging_id = id::foo_ro_arit_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_foo_ro_arit_1_foo_ro_arit_app_0,call::caller_foo_ro_arit_2_foo_ro_arit_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_foo_ro_arit_1> {static constexpr impl this_impl = impl::caller_foo_ro_arit_1;
static constexpr id belonging_id = id::caller_foo_ro_arit_1;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_foo_ro_arit_1_foo_ro_arit_app_0>;
};template <> struct traits<impl::caller_foo_ro_arit_2> {static constexpr impl this_impl = impl::caller_foo_ro_arit_2;
static constexpr id belonging_id = id::caller_foo_ro_arit_2;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_foo_ro_arit_2_foo_ro_arit_app_0>;
};template <> struct traits<impl::foo_rw_arit> {static constexpr impl this_impl = impl::foo_rw_arit;
static constexpr id belonging_id = id::foo_rw_arit_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,int>;
using call_sequence = util::sequence::enum_t<call,call::caller_foo_rw_arit_1_foo_rw_arit_app_0,call::caller_foo_rw_arit_2_foo_rw_arit_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_foo_rw_arit_1> {static constexpr impl this_impl = impl::caller_foo_rw_arit_1;
static constexpr id belonging_id = id::caller_foo_rw_arit_1;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_foo_rw_arit_1_foo_rw_arit_app_0>;
};template <> struct traits<impl::caller_foo_rw_arit_2> {static constexpr impl this_impl = impl::caller_foo_rw_arit_2;
static constexpr id belonging_id = id::caller_foo_rw_arit_2;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<int>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_foo_rw_arit_2_foo_rw_arit_app_0>;
};template <> struct traits<call::caller_foo_ro_arit_1_foo_ro_arit_app_0> {static constexpr call this_call = call::caller_foo_ro_arit_1_foo_ro_arit_app_0;
static constexpr impl belonging_impl = impl::foo_ro_arit;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<0,float>>,int>;
};template <> struct traits<call::caller_foo_ro_arit_2_foo_ro_arit_app_0> {static constexpr call this_call = call::caller_foo_ro_arit_2_foo_ro_arit_app_0;
static constexpr impl belonging_impl = impl::foo_ro_arit;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<0,float>>,int>;
};template <> struct traits<call::caller_foo_rw_arit_1_foo_rw_arit_app_0> {static constexpr call this_call = call::caller_foo_rw_arit_1_foo_rw_arit_app_0;
static constexpr impl belonging_impl = impl::foo_rw_arit;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<0,float>>,int>;
};template <> struct traits<call::caller_foo_rw_arit_2_foo_rw_arit_app_0> {static constexpr call this_call = call::caller_foo_rw_arit_2_foo_rw_arit_app_0;
static constexpr impl belonging_impl = impl::foo_rw_arit;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<0,float>>,int>;
};}