//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Proxy;
export import App.Graph;
export import SteelRT.Util.Types;
export import SteelRT.Util.Sequence;
export import SteelRT.Util.FwDeclarations.App;
export import SteelRT.Util.Predicates.App;
export import SteelRT.Task.Descriptor;
export import SteelRT.Task.Dispatcher;
export import SteelRT.Work.Descriptor.Global;
export import SteelRT.Dep.MakeAsync;
export import SteelRT.Dep.Guard.Backend;
export import SteelRT.Dep.Guard.Frontend;
export import SteelRT.Dep.Wrap;
export import <type_traits>;
export import <stdexcept>;
void foo_ro_multiple_point(std::add_pointer_t<std::add_const_t<float>>,int);
task::coro::dispatcher<app::impl::caller1_ro_multiple_point> caller1_ro_multiple_point(task::attr::descriptor& );
task::coro::dispatcher<app::impl::caller2_ro_multiple_point> caller2_ro_multiple_point(task::attr::descriptor& ,int,int,int);
void foo_rw_multiple_point(std::add_pointer_t<float>,int);
task::coro::dispatcher<app::impl::caller1_rw_multiple_point> caller1_rw_multiple_point(task::attr::descriptor& );
task::coro::dispatcher<app::impl::caller2_rw_multiple_point> caller2_rw_multiple_point(task::attr::descriptor& ,int,int,int);
export
namespace app{
template <>
class kernel_proxy<impl::foo_ro_multiple_point> {
  static constexpr impl this_impl = impl::foo_ro_multiple_point;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_ro_multiple_point( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller1_ro_multiple_point> {
public:
  static constexpr impl this_impl = impl::caller1_ro_multiple_point;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller1_ro_multiple_point( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class dispatcher_proxy<impl::caller2_ro_multiple_point> {
public:
  static constexpr impl this_impl = impl::caller2_ro_multiple_point;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller2_ro_multiple_point( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_rw_multiple_point> {
  static constexpr impl this_impl = impl::foo_rw_multiple_point;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_rw_multiple_point( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller1_rw_multiple_point> {
public:
  static constexpr impl this_impl = impl::caller1_rw_multiple_point;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller1_rw_multiple_point( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class dispatcher_proxy<impl::caller2_rw_multiple_point> {
public:
  static constexpr impl this_impl = impl::caller2_rw_multiple_point;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller2_rw_multiple_point( std::forward<DispatcherArgs>(args) ... ) );
  }
};
}