////// Autogenerated code

export module App.ProxyKernelGenerated;



export import App.Traits;

export import App.UserTranslatedKernel;


import SteelRT.Util.Sequence;
import SteelRT.Util.App;

import <tuple>;
import <any>;
import <functional>;


namespace app {

// kernel_proxy of impl::poison_pill must not be defined


export
template <>
class kernel_proxy<impl::ro_region> {
  static constexpr impl this_impl = impl::ro_region;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;

public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    kernel_ro_region( std::forward<KernelArgs>(args) ... );
  }
};

export
template <>
class kernel_proxy<impl::rw_region> {
  static constexpr impl this_impl = impl::rw_region;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;

public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    kernel_rw_region( std::forward<KernelArgs>(args) ... );
  }
};



} // namespace app
