//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Enum;
import SteelRT.Util.Types;
import SteelRT.Util.Values;
import SteelRT.Util.Sequence;
import SteelRT.Instrument.FwDeclarations;
import <cstdio>;
export
namespace app{enum class call : enum_uint_t {init_caller_v0_init_app_0 = 2};using enabled_calls = util::sequence::enum_t<call,call::init_caller_v0_init_app_0>;}
export
namespace instrument::event{template <> struct type<app::call>{static constexpr const char * name = "call";
static constexpr const enum_type_id_t type_id = 0;
static constexpr bool instrumentable = true;
};template <> struct value<app::call::init_caller_v0_init_app_0>{static constexpr const char * name = "init_caller_v0_init_app_0";}
;}export
namespace app{enum class id : enum_uint_t {init_app = 2,init_caller_v0 = 3};using enabled_ids = util::sequence::enum_t<id,id::init_app,id::init_caller_v0>;}
export
namespace instrument::event{template <> struct type<app::id>{static constexpr const char * name = "id";
static constexpr const enum_type_id_t type_id = 1;
static constexpr bool instrumentable = true;
};template <> struct value<app::id::init_app>{static constexpr const char * name = "init_app";}
;template <> struct value<app::id::init_caller_v0>{static constexpr const char * name = "init_caller_v0";}
;}export
namespace app{enum class impl : enum_uint_t {init_caller_v0 = 2,init_v0 = 3};using enabled_impls = util::sequence::enum_t<impl,impl::init_caller_v0,impl::init_v0>;}
export
namespace instrument::event{template <> struct type<app::impl>{static constexpr const char * name = "impl";
static constexpr const enum_type_id_t type_id = 2;
static constexpr bool instrumentable = true;
};template <> struct value<app::impl::init_caller_v0>{static constexpr const char * name = "init_caller_v0";}
;template <> struct value<app::impl::init_v0>{static constexpr const char * name = "init_v0";}
;}