//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Enum;
import SteelRT.Util.Types;
import SteelRT.Util.Values;
import SteelRT.Util.Sequence;
import SteelRT.Instrument.FwDeclarations;
import <cstdio>;
export
namespace app{enum class call : enum_uint_t {caller_wo_fooapp_wo_0 = 2};using enabled_calls = util::sequence::enum_t<call,call::caller_wo_fooapp_wo_0>;}
export
namespace instrument::event{template <> struct type<app::call>{static constexpr const char * name = "call";
static constexpr const enum_type_id_t type_id = 0;
static constexpr bool instrumentable = true;
};template <> struct value<app::call::caller_wo_fooapp_wo_0>{static constexpr const char * name = "caller_wo_fooapp_wo_0";}
;}export
namespace app{enum class id : enum_uint_t {caller_wo = 2,fooapp_wo = 3};using enabled_ids = util::sequence::enum_t<id,id::caller_wo,id::fooapp_wo>;}
export
namespace instrument::event{template <> struct type<app::id>{static constexpr const char * name = "id";
static constexpr const enum_type_id_t type_id = 1;
static constexpr bool instrumentable = true;
};template <> struct value<app::id::caller_wo>{static constexpr const char * name = "caller_wo";}
;template <> struct value<app::id::fooapp_wo>{static constexpr const char * name = "fooapp_wo";}
;}export
namespace app{enum class impl : enum_uint_t {caller_wo = 2,foo_wo = 3};using enabled_impls = util::sequence::enum_t<impl,impl::caller_wo,impl::foo_wo>;}
export
namespace instrument::event{template <> struct type<app::impl>{static constexpr const char * name = "impl";
static constexpr const enum_type_id_t type_id = 2;
static constexpr bool instrumentable = true;
};template <> struct value<app::impl::caller_wo>{static constexpr const char * name = "caller_wo";}
;template <> struct value<app::impl::foo_wo>{static constexpr const char * name = "foo_wo";}
;}