//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import Plat.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Dep.Dim.View;
export
namespace app{
template <> struct traits<id::dot_prod_app>{using impl_sequence = util::sequence::enum_t<impl,impl::dot_prod_v1,impl::dot_prod_v2>;};template <> struct traits<id::reduce_app>{using impl_sequence = util::sequence::enum_t<impl,impl::reduce>;};template <> struct traits<impl::dot_prod_v1> {static constexpr impl this_impl = impl::dot_prod_v1;
static constexpr id belonging_id = id::dot_prod_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_pointer_t<std::add_const_t<float>>,std::add_pointer_t<std::add_const_t<float>>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call,call::dot_prod_v2_dot_prod_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::reduce> {static constexpr impl this_impl = impl::reduce;
static constexpr id belonging_id = id::reduce_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_pointer_t<std::add_const_t<float>>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call,call::dot_prod_v2_reduce_app_1>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::dot_prod_v2> {static constexpr impl this_impl = impl::dot_prod_v2;
static constexpr id belonging_id = id::dot_prod_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_pointer_t<std::add_const_t<float>>,std::add_pointer_t<std::add_const_t<float>>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::dot_prod_v2_dot_prod_app_0,call::dot_prod_v2_reduce_app_1>;
};template <> struct traits<call::dot_prod_v2_dot_prod_app_0> {static constexpr call this_call = call::dot_prod_v2_dot_prod_app_0;
static constexpr impl belonging_impl = impl::dot_prod_v1;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,dep::guard::bnd::readable<dep::dim::view<1,const float>>,dep::guard::bnd::readable<dep::dim::view<1,const float>>,const unsigned>;
};template <> struct traits<call::dot_prod_v2_reduce_app_1> {static constexpr call this_call = call::dot_prod_v2_reduce_app_1;
static constexpr impl belonging_impl = impl::reduce;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<0,float>>,dep::guard::bnd::readable<dep::dim::view<1,float>>,const unsigned>;
};}