//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import Plat.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Dep.Dim.View;
export
namespace app{
template <> struct traits<id::init_app>{using impl_sequence = util::sequence::enum_t<impl,impl::init_v0>;};template <> struct traits<id::init_caller_v0>{using impl_sequence = util::sequence::enum_t<impl,impl::init_caller_v0>;};template <> struct traits<impl::init_v0> {static constexpr impl this_impl = impl::init_v0;
static constexpr id belonging_id = id::init_app;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,float>;
using call_sequence = util::sequence::enum_t<call,call::init_caller_v0_init_app_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::init_caller_v0> {static constexpr impl this_impl = impl::init_caller_v0;
static constexpr id belonging_id = id::init_caller_v0;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::init_caller_v0_init_app_0>;
};template <> struct traits<call::init_caller_v0_init_app_0> {static constexpr call this_call = call::init_caller_v0_init_app_0;
static constexpr impl belonging_impl = impl::init_v0;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,float>;
};}