//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Graph;
export import App.Enum;
import Plat.Enum;
import SteelRT.Util.Sequence;
import SteelRT.Util.Types;
import SteelRT.Util.Tuple;
import SteelRT.Util.FwDeclarations.App;
import SteelRT.Dep.Guard.Backend;
import SteelRT.Dep.Dim.View;
export
namespace app{
template <> struct traits<id::caller_different_callee>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_different_callee>;};template <> struct traits<id::caller_same_callee>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_same_callee>;};template <> struct traits<id::caller_same_n_different_callee>{using impl_sequence = util::sequence::enum_t<impl,impl::caller_same_n_different_callee>;};template <> struct traits<id::fooapp_callee_x>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_callee_x>;};template <> struct traits<id::fooapp_callee_y>{using impl_sequence = util::sequence::enum_t<impl,impl::foo_callee_y>;};template <> struct traits<impl::foo_callee_x> {static constexpr impl this_impl = impl::foo_callee_x;
static constexpr id belonging_id = id::fooapp_callee_x;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call,call::caller_same_callee_fooapp_callee_x_0,call::caller_same_callee_fooapp_callee_x_1,call::caller_same_callee_fooapp_callee_x_2,call::caller_different_callee_fooapp_callee_x_0,call::caller_same_n_different_callee_fooapp_callee_x_0>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::foo_callee_y> {static constexpr impl this_impl = impl::foo_callee_y;
static constexpr id belonging_id = id::fooapp_callee_y;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<std::add_const_t<float>>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call,call::caller_different_callee_fooapp_callee_y_1,call::caller_same_n_different_callee_fooapp_callee_y_1,call::caller_same_n_different_callee_fooapp_callee_y_2>;
using dispatch_sequence = util::sequence::enum_t<call>;
};template <> struct traits<impl::caller_same_callee> {static constexpr impl this_impl = impl::caller_same_callee;
static constexpr id belonging_id = id::caller_same_callee;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_same_callee_fooapp_callee_x_0,call::caller_same_callee_fooapp_callee_x_1,call::caller_same_callee_fooapp_callee_x_2>;
};template <> struct traits<impl::caller_different_callee> {static constexpr impl this_impl = impl::caller_different_callee;
static constexpr id belonging_id = id::caller_different_callee;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_different_callee_fooapp_callee_x_0,call::caller_different_callee_fooapp_callee_y_1>;
};template <> struct traits<impl::caller_same_n_different_callee> {static constexpr impl this_impl = impl::caller_same_n_different_callee;
static constexpr id belonging_id = id::caller_same_n_different_callee;
static constexpr plat::arch arch_value = plat::arch::x86_64;
using arg_tuple_type = util::tuple_t<std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>>;
using call_sequence = util::sequence::enum_t<call>;
using dispatch_sequence = util::sequence::enum_t<call,call::caller_same_n_different_callee_fooapp_callee_x_0,call::caller_same_n_different_callee_fooapp_callee_y_1,call::caller_same_n_different_callee_fooapp_callee_y_2>;
};template <> struct traits<call::caller_same_callee_fooapp_callee_x_0> {static constexpr call this_call = call::caller_same_callee_fooapp_callee_x_0;
static constexpr impl belonging_impl = impl::foo_callee_x;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_same_callee_fooapp_callee_x_1> {static constexpr call this_call = call::caller_same_callee_fooapp_callee_x_1;
static constexpr impl belonging_impl = impl::foo_callee_x;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_same_callee_fooapp_callee_x_2> {static constexpr call this_call = call::caller_same_callee_fooapp_callee_x_2;
static constexpr impl belonging_impl = impl::foo_callee_x;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_different_callee_fooapp_callee_x_0> {static constexpr call this_call = call::caller_different_callee_fooapp_callee_x_0;
static constexpr impl belonging_impl = impl::foo_callee_x;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_different_callee_fooapp_callee_y_1> {static constexpr call this_call = call::caller_different_callee_fooapp_callee_y_1;
static constexpr impl belonging_impl = impl::foo_callee_y;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_same_n_different_callee_fooapp_callee_x_0> {static constexpr call this_call = call::caller_same_n_different_callee_fooapp_callee_x_0;
static constexpr impl belonging_impl = impl::foo_callee_x;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::writable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_same_n_different_callee_fooapp_callee_y_1> {static constexpr call this_call = call::caller_same_n_different_callee_fooapp_callee_y_1;
static constexpr impl belonging_impl = impl::foo_callee_y;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<1,float>>,unsigned>;
};template <> struct traits<call::caller_same_n_different_callee_fooapp_callee_y_2> {static constexpr call this_call = call::caller_same_n_different_callee_fooapp_callee_y_2;
static constexpr impl belonging_impl = impl::foo_callee_y;
using arg_tuple_type = util::tuple_t<dep::guard::bnd::readable<dep::dim::view<1,float>>,unsigned>;
};}