//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Proxy;
export import App.Graph;
export import SteelRT.Util.Types;
export import SteelRT.Util.Sequence;
export import SteelRT.Util.FwDeclarations.App;
export import SteelRT.Util.Predicates.App;
export import SteelRT.Task.Descriptor;
export import SteelRT.Task.Dispatcher;
export import SteelRT.Work.Descriptor.Global;
export import SteelRT.Dep.MakeAsync;
export import SteelRT.Dep.Guard.Backend;
export import SteelRT.Dep.Guard.Frontend;
export import SteelRT.Dep.Wrap;
export import <type_traits>;
export import <stdexcept>;
void foo_whole_ro(std::add_pointer_t<std::add_const_t<float>>,int);
task::coro::dispatcher<app::impl::caller_ro> caller_ro(task::attr::descriptor& ,int);
void foo_portion_ro(std::add_pointer_t<std::add_const_t<float>>,int,int);
task::coro::dispatcher<app::impl::caller_ro> caller_ro(task::attr::descriptor& ,int,int);
void foo_whole_rw(std::add_pointer_t<float>,int);
task::coro::dispatcher<app::impl::caller_rw> caller_rw(task::attr::descriptor& ,int);
void foo_portion_rw(std::add_pointer_t<std::add_const_t<float>>,int,int);
task::coro::dispatcher<app::impl::caller_rw> caller_rw(task::attr::descriptor& ,int,int);
export
namespace app{
template <>
class kernel_proxy<impl::foo_whole_ro> {
  static constexpr impl this_impl = impl::foo_whole_ro;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_whole_ro( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_ro> {
public:
  static constexpr impl this_impl = impl::caller_ro;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_ro( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_portion_ro> {
  static constexpr impl this_impl = impl::foo_portion_ro;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_portion_ro( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_ro> {
public:
  static constexpr impl this_impl = impl::caller_ro;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_ro( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_whole_rw> {
  static constexpr impl this_impl = impl::foo_whole_rw;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_whole_rw( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_rw> {
public:
  static constexpr impl this_impl = impl::caller_rw;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_rw( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class kernel_proxy<impl::foo_portion_rw> {
  static constexpr impl this_impl = impl::foo_portion_rw;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_portion_rw( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_rw> {
public:
  static constexpr impl this_impl = impl::caller_rw;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_rw( std::forward<DispatcherArgs>(args) ... ) );
  }
};
}