//////////////////////////////////////
// 
// Autogenerated file. Do not modify. 
// 
//////////////////////////////////////

export module App.Proxy;
export import App.Graph;
export import SteelRT.Util.Types;
export import SteelRT.Util.Sequence;
export import SteelRT.Util.FwDeclarations.App;
export import SteelRT.Util.Predicates.App;
export import SteelRT.Task.Descriptor;
export import SteelRT.Task.Dispatcher;
export import SteelRT.Work.Descriptor.Global;
export import SteelRT.Dep.MakeAsync;
export import SteelRT.Dep.Guard.Backend;
export import SteelRT.Dep.Guard.Frontend;
export import SteelRT.Dep.Wrap;
export import <type_traits>;
export import <stdexcept>;
void foo_callee_x(std::add_pointer_t<float>,std::add_const_t<unsigned>);
void foo_callee_y(std::add_pointer_t<std::add_const_t<float>>,std::add_const_t<unsigned>);
task::coro::dispatcher<app::impl::caller_same_callee> caller_same_callee(task::attr::descriptor& ,std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>);
task::coro::dispatcher<app::impl::caller_different_callee> caller_different_callee(task::attr::descriptor& ,std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>);
task::coro::dispatcher<app::impl::caller_same_n_different_callee> caller_same_n_different_callee(task::attr::descriptor& ,std::add_pointer_t<float>,std::add_const_t<unsigned>,std::add_const_t<unsigned>);
export
namespace app{
template <>
class kernel_proxy<impl::foo_callee_x> {
  static constexpr impl this_impl = impl::foo_callee_x;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_callee_x( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class kernel_proxy<impl::foo_callee_y> {
  static constexpr impl this_impl = impl::foo_callee_y;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
public:
  template <typename... KernelArgs>
  static void run(KernelArgs&&... args) {
    foo_callee_y( std::forward<KernelArgs>(args) ... );
  }
};
template <>
class dispatcher_proxy<impl::caller_same_callee> {
public:
  static constexpr impl this_impl = impl::caller_same_callee;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_same_callee( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class dispatcher_proxy<impl::caller_different_callee> {
public:
  static constexpr impl this_impl = impl::caller_different_callee;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_different_callee( std::forward<DispatcherArgs>(args) ... ) );
  }
};
template <>
class dispatcher_proxy<impl::caller_same_n_different_callee> {
public:
  static constexpr impl this_impl = impl::caller_same_n_different_callee;
  using arg_tuple_type = typename app::traits<this_impl>::arg_tuple_type;
  template <typename... DispatcherArgs>
  static
  std::shared_ptr<task::coro::dispatcher<this_impl>>
  create(DispatcherArgs&&... args) noexcept {
    return std::make_shared< task::coro::dispatcher<this_impl> >( caller_same_n_different_callee( std::forward<DispatcherArgs>(args) ... ) );
  }
};
}